services:
    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - mariadb
            - redis
        networks:
            - biblioteca-net

    # db mariadb
    mariadb:
        image: mariadb:11.3
        #restart: unless-stopped
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_TCP_PORT: 3307
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - mariadb-data:/var/lib/mysql
        ports:
            - "3307:3307"
        command:
            --max_allowed_packet=32505856
        networks:
            - biblioteca-net      

    # Redis Server
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
        ports:
            - 6379:6379
        networks:
            - biblioteca-net

    # nginx
    nginx:
        image: nginx:alpine
        #restart: unless-stopped
        ports:
            - "8989:89"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - biblioteca-net

networks:
    biblioteca-net:
        name: biblioteca-net
        driver: bridge

volumes:
    mariadb-data:
